services:
  - type: web
    name: persona-render
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y fonts-ipaexfont fonts-ipafont-gothic fonts-ipafont-mincho
      fc-cache -f -v
      rm -rf ~/.cache/matplotlib
      pip install --upgrade pip && pip install -r requirements.txt
      python -c "import matplotlib.font_manager; matplotlib.font_manager._rebuild()"
      echo "Build timestamp: $(date)"
    startCommand: gunicorn backend.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 300 --graceful-timeout 120 --worker-connections 500 --max-requests 100 --max-requests-jitter 20
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: PERSISTENT_DISK_PATH
        value: /var/app_settings
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: app-settings
      mountPath: /var/app_settings
      sizeGB: 1
